language: ruby
cache: bundler
script: 'bundle exec rake'
rvm:
  - 2.2.5
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libtag1-dev

notifications:
  email:
    recipients:
      - tomas.celizna@gmail.com
    on_failure: change
    on_success: never
